### PR TITLE
Improvement/sc 233 mobile refactor and clean up code

### PR DESCRIPTION
**Pull request by tsisko20**
Cleaned up all the mobile code and added some UI improvements and fixes for possible crashes that were happening.

### CODE REVIEW

**Review by lraknic — CHANGES_REQUESTED** [review]
I have problems with loading app on emulator because emulator doesn't have NFC.
image

**Review by lraknic — APPROVED** [review]
Everything looks good. Good job!

**Review by irosic20 — APPROVED** [review]
Everything looks good!

**Review by mkajic20 — APPROVED** [review]
Everything seems good and app works perfectly! Nice job!

**Review by lgaljer20 — APPROVED** [review]
Everything seems good. Nice job.

**Pull request merged**
