### PR TITLE
hotfix/dependencies-and-compileSdk-fix

### PR DESCRIPTION
**Pull request by lraknic**
Changed version of dependencies and compileSdk in login_google and login_email_password. This changes will fix errors with gradle build.

### CODE REVIEW

**Review by tsisko20 — APPROVED** [review]
Everything is good.

**Review by irosic20 — CHANGES_REQUESTED** [review]
I tried Google Login, and it is not letting me log in to the app, while email/password login does. I looked into Logcat and saw this error:

> win=Window{35c44f8 u0 org.foi.air.smartcharger/com.google.android.gms.auth.api.signin.internal.SignInHubActivity EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6539 com.android.server.wm.ActivityRecord.destroySurfaces:6520 com.android.server.wm.WindowState.onExitAnimationDone:5995 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda10.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.ActivityRecord.onAnimationFinished:8607 com.android.server.wm.WindowContainer$$ExternalSyntheticLambda4.onAnimationFinished:2

**Comment by irosic20** [comment]
After further testing I no longer get the error form my previous comment but Google login still doesn't work.

**Review by irosic20 — APPROVED** [review]

**Comment by lraknic** [comment]
Fixing Google login will be a new task in upcoming sprint.

**Pull request merged**
