### PR TITLE
First deployment of the mobile application

### PR DESCRIPTION
**Pull request by irosic20**
This pull request is the first deployment of the mobile application.

It contains the following features:

User navigation
User registration page
User login page (login with email and password, google login)
User logout
User RFID card management page
User charging history page

Charging connection page
Charger selector page
Charging simulator page

### CODE REVIEW

**Review by lraknic — APPROVED** [review]
Everything looks good.

**Review by tsisko20 — APPROVED** [review]
Everything is good.

**Review by mkajic20 — APPROVED** [review]
App has all of the planned functionalities and everything works as it should.

**Review by lgaljer20 — APPROVED** [review]
Everything is working!

**Pull request merged**
